/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "my_switch.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int state = 0;
	int prev_sw = 0;
	int curr_sw = 0;
	led_init();
	switch_init();
	while (1)
		{
			/* Read switch */
			curr_sw = (GPIOA->IDR & BV(0));

			/* Detect switch press (rising edge) */
			if (curr_sw && !prev_sw)
			{
				state++;

				if (state > 3)
					state = 1;

				/* State-based LED control */
				if (state == 1)
				{
					/* Green ON, Blue OFF */
					GPIOD->ODR |=  BV(GREEN_LED);
					GPIOD->ODR &= ~BV(BLUE_LED);
				}
				else if (state == 2)
				{
					/* Green ON, Blue ON */
					GPIOD->ODR |= BV(GREEN_LED) | BV(BLUE_LED);
				}
				else if (state == 3)
				{
					/* Both OFF */
					GPIOD->ODR &= ~(BV(GREEN_LED) | BV(BLUE_LED));
				}

				/* Simple debounce delay */
				for (volatile int i = 0; i < 200000; i++);
			}

			prev_sw = curr_sw;
		}
}







